### ISSUE TITLE
Update the "Code of Conduct"

### ISSUE THREAD

**Issue by thejohnjansen** [web-platform-tests/editor#5]
This repo was owned by MicrosoftEdge and Microsoft before being migrated to Web-Platform-Tests. The code of conduct still reference's Microsoft. It should be updated to the WPT code.

**Comment by foolip** [comment]
WPT doesn't have a CoC yet, but there's a proposed one in https://github.com/web-platform-tests/wpt/pull/7520. That really just needs to go through the RFC process to be done.

**Comment by thejohnjansen** [comment]
Fixed.
