### ISSUE TITLE
Change the Code of Conduct to point to the new W-P-T CoC

### ISSUE THREAD

**Issue by thejohnjansen** [web-platform-tests/editor#7]
Once the new CoC is approved, link this repo's CoC to that.

**Comment by thejohnjansen** [comment]
I cannot find the new CoC for WPT. @jgraham or @stephenmcgruer can you point me to it?

**Comment by jgraham** [comment]
https://github.com/web-platform-tests/wpt/blob/master/CODE_OF_CONDUCT.md

**Comment by thejohnjansen** [comment]
Oh sheesh. Thanks @jgraham . I searched for "conduct" but didn't see that rather obvious result.

**Comment by thejohnjansen** [comment]
Fixed this.
